# Bu kod sarapcanagii ve primatzeka' ya aittir. İstediginiz gibi kullanabilirsiniz.
name: Update Stream URLs

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests gitpython
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
    - name: Run updater script
      run: python stream_updater.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}